mysql:
  host: 172.28.64.1
  port: 3306
  database: user-sys
  username: root
  password: guang

redis:
  host: 172.28.64.1
  port: 6379

PORT: 5000
SECRET: FGNMfvbnmVBNM23456789$%^&*(*&^%$%^&*&^%$%^&^%$%^&^%$#)