FROM golang:latest as build

ENV GOPROXY https://goproxy.io
ENV GO111MODULE on

WORKDIR /go/cache

ADD go.mod .
ADD go.sum .
RUN go mod download

WORKDIR /go/release

ADD . .

RUN GOOS=linux CGO_ENABLED=0 ENV=prod go build -ldflags="-s -w" -installsuffix cgo -o imcs-design-go main.go

FROM scratch as prod

EXPOSE 5000

COPY --from=build /go/release/golang /
COPY --from=build /go/release/application.yaml /
CMD ["./imcs-design-go"]