basePath: /v1
definitions:
  dto.LoginDto:
    properties:
      email:
        type: string
      jwt:
        type: string
    type: object
  vo.LoginVo:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  vo.RegisterVo:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: 127.0.0.1:5000
info:
  contact:
    email: miaoyu200@qq.com
    name: miaoyu
    url: http://coolcat.io/support
  description: test to
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/go-programming-tour-book
  title: 博客系统
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录账户, 获取 token
      parameters:
      - description: User login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/vo.LoginVo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: number
              data:
                $ref: '#/definitions/dto.LoginDto'
              message:
                type: string
            type: object
      summary: 登录
      tags:
      - login
  /register:
    post:
      consumes:
      - application/json
      description: 账户注册
      parameters:
      - description: 用户注册
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/vo.RegisterVo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: number
              message:
                type: string
            type: object
      summary: 注册
      tags:
      - register
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
