basePath: /v1
definitions:
  dto.LoginDto:
    properties:
      email:
        type: string
      jwt:
        type: string
    type: object
  vo.LoginVo:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: 127.0.0.1:5000
info:
  contact:
    email: miaoyu200@qq.com
    name: miaoyu
    url: http://coolcat.io/support
  description: This is a simple api server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Apiserver API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录账户, 获取 token
      parameters:
      - description: User login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/vo.LoginVo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginDto'
      summary: 登录
      tags:
      - login
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
